name: Deploy to AWS App Runner

on:
  push:
    branches: [ "main" ]  # or master, whichever your repo uses

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} \
          | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}

      - name: Build, Tag, and Push Docker image
        run: |
          IMAGE_TAG=latest
          docker build -t ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:$IMAGE_TAG .
          docker push ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:$IMAGE_TAG

      - name: Deploy to App Runner
        run: |
          aws apprunner start-deployment --service-arn arn:aws:apprunner:ap-south-1:697957568941:service/madd/arn:aws:apprunner:ap-south-1:697957568941:service/madd/5f02fb9213a046a38ab9084e4759a549
